baseURL = "https://cynthiabelleza.com/"
languageCode = "en-us"
title = "Cynthia Belleza"
theme = "dream"
defaultContentLanguage = "en"

googleAnalytics = "..."
enableRobotsTXT = true

#Paginate = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  
  background = "#fff"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  # backgroundDark = "#222"
  backgroundImageDark = "/me/background.jpg"
  darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  images = ["me/background.jpg"]

  author = "Cynthia Pimentel Belleza Bernardino"
  description = "Avatar"
  avatar = "/img/avatar.jpg"
  headerTitle = "Cynthia Belleza's Portfolio"
  motto = "Passionate about organization, understanding people needs and storytelling"
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  rss = true

  #utterancesRepo = "g1eny0ung/g1eny0ung.github.io"

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "cynthia.belleza@gmail.com"
  twitter = "cynthia_belleza"
  # facebook = "g1eny0ung"
  # instagram = "g1enyy0ung"
  # mastodon = ""
  linkedin = "belleza"
  github = "cynthiabelleza"
  # stackoverflow = "5676489/g1eny0ung"
  # codepen = "g1eny0ung"

  siteStartYear = 2021

  favicon = "/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["clojure", "ocaml"]
  highlightjsTheme = "tomorrow"
  highlightjsThemeDark = "tomorrow-night"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true

  [params.advanced]
    customCSS = ["css/custom.css"]
    customJS = []